# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.20.dev23+gee0dd82.d20220601'
version_tuple = (0, 1, 20, 'dev23', 'gee0dd82.d20220601')
